version: "3"
services:
  mysql:
    container_name: nacos_mysql
    image: mysql:8.0
    env_file: 
      - ./env/mysql.env
    volumes: 
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - /data/mysql:/var/lib/mysql
    ports: 
      - "3308:3306"
      - "33066:33060"
    command: 
      --innodb_use_native_aio=0
      --max_connections=100
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      # --lower_case_table_names=1
    networks: 
      - minacloud_net

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    env_file: 
      - ./env/nacos.env
    volumes: 
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
      - /data/logs/nacos:/home/nacos/logs
    ports: 
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
    networks: 
      - minacloud_net
    depends_on: 
      - mysql

networks: 
  minacloud_net:
    driver: bridge
        